(()=>{'use strict';
function css(href,key){if(document.querySelector(`link[data-${key}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='1';document.head.appendChild(l)}
function script(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.async=false;s.dataset[key]='1';document.head.appendChild(s)}
function installMutationGate(){if(window.__EDITORIAL_MO_GATE_V36)return;window.__EDITORIAL_MO_GATE_V36=true;window.EDITORIAL_DND_SETTLING=false;const Native=window.MutationObserver;if(!Native)return;window.MutationObserver=class EditorialMutationObserver extends Native{constructor(cb){super((records,obs)=>{if(window.EDITORIAL_DND_SETTLING&&records.some(r=>r.target?.id==='weekBoard'||r.target?.closest?.('#weekBoard')))return;cb(records,obs)})}}}
function patchVersionedLinks(){const manifest=document.querySelector('link[rel="manifest"]');if(manifest)manifest.href='./manifest.webmanifest?v=39';document.querySelectorAll('a[href]').forEach(a=>{let h=a.getAttribute('href')||'';h=h.replace(/\?v=(29|30|31|32|33|34|35|36|37|38)/g,'?v=39');a.setAttribute('href',h)})}
async function registerSW(){if(!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v=39',{scope:'./'});reg.update?.()}catch(e){console.info('Service Worker no disponible; la app continúa online.',e)}}
function boot(){installMutationGate();
 ['30','31','32','33','35','36','37','38','39'].forEach(v=>css(`./css/system-v${v}.css?v=39`,`editorialV${v}`));
 script('./js/progress-v32.js?v=39','editorialProgressV32');script('./js/planner-v30.js?v=39','editorialPlannerV30');script('./js/mcp-ui-v31.js?v=39','editorialMcpV31');script('./js/activity-v32.js?v=39','editorialActivityV32');script('./js/smooth-ui-v34.js?v=39','editorialSmoothV34');script('./js/no-flash-v35.js?v=39','editorialNoFlashV35');script('./js/flexible-week-v33.js?v=39','editorialFlexibleWeekV33');script('./js/dnd-v36.js?v=39','editorialDndV36');script('./js/catalog-v37.js?v=39','editorialCatalogV37');script('./js/catalog-v38.js?v=39','editorialCatalogV38');
 patchVersionedLinks();registerSW();document.documentElement.dataset.editorialVersion='3.9'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();