(()=>{'use strict';
const VERSION='4.7';
const NATIVE_DESKTOP=/EditorialEmulatorDesktop/i.test(navigator.userAgent||'');
function css(href,key){if(document.querySelector(`link[data-${key}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='1';document.head.appendChild(l)}
function load(src,key){return new Promise(resolve=>{if(document.querySelector(`script[data-${key}]`)){resolve(true);return}const s=document.createElement('script');s.src=src;s.async=false;s.dataset[key]='1';let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);resolve(ok)};const timer=setTimeout(()=>finish(false),6000);s.onload=()=>finish(true);s.onerror=()=>finish(false);document.head.appendChild(s)})}
function patchVersion(){document.documentElement.dataset.editorialVersion=VERSION;const m=document.querySelector('meta[name="editorial-emulator-build"]');if(m)m.content=VERSION;document.title='Editorial Emulator V4.7';const startup=document.querySelector('#startup .eyebrow');if(startup&&/Editorial Emulator/i.test(startup.textContent||''))startup.textContent='Editorial Emulator V4.7';const manifest=document.querySelector('link[rel="manifest"]');if(manifest)manifest.href='./manifest.webmanifest?v=47';document.querySelectorAll('a[href]').forEach(a=>{let h=a.getAttribute('href')||'';h=h.replace(/\?v=(29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46)/g,'?v=47');a.setAttribute('href',h)})}
async function registerSW(){if(NATIVE_DESKTOP||!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v=47',{scope:'./',updateViaCache:'none'});reg.update?.()}catch(e){console.info('Service Worker no disponible; la app sigue local-first.',e)}}
async function boot(){patchVersion();['27','28','29','30','33','36','37','38','39','41','42','43','44','45','46','47'].forEach(v=>css(`./css/system-v${v}.css?v=47`,`editorialV${v}`));const modules=[['./js/runtime-v27.js?v=47','editorialRuntimeV27'],['./js/ux-v28.js?v=47','editorialUxV47'],['./js/planner-v44.js?v=47','editorialPlannerV44'],['./js/planner-layout-v46.js?v=47','editorialPlannerLayoutV46'],['./js/flexible-week-v33.js?v=47','editorialFlexibleWeekV47'],['./js/catalog-v45.js?v=47','editorialCatalogV45'],['./js/catalog-portal-v47.js?v=47','editorialCatalogPortalV47'],['./js/dnd-v40.js?v=47','editorialDndV40'],['./js/smart-drag-v42.js?v=47','editorialSmartDragV42'],['./js/workflow-data-v43.js?v=47','editorialWorkflowDataV43'],['./js/workflow-ui-v44.js?v=47','editorialWorkflowUiV44'],['./js/workflow-create-v43.js?v=47','editorialWorkflowCreateV43'],['./js/workflow-filters-v43.js?v=47','editorialWorkflowFiltersV43'],['./js/workflow-sync-v43.js?v=47','editorialWorkflowSyncV43']];for(const [src,key] of modules)await load(src,key);import('./liquidglass-v28.js?v=47').catch(()=>{});patchVersion();document.documentElement.dataset.editorialBoot='ready';window.dispatchEvent(new CustomEvent('editorial:boot-ready',{detail:{version:VERSION,nativeDesktop:NATIVE_DESKTOP}}));registerSW()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
