(()=>{'use strict';
const VERSION='4.4';
const NATIVE_DESKTOP=/EditorialEmulatorDesktop/i.test(navigator.userAgent||'');
function css(href,key){if(document.querySelector(`link[data-${key}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='1';document.head.appendChild(l)}
function load(src,key){return new Promise(resolve=>{if(document.querySelector(`script[data-${key}]`)){resolve(true);return}const s=document.createElement('script');s.src=src;s.async=false;s.dataset[key]='1';let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);resolve(ok)};const timer=setTimeout(()=>finish(false),6000);s.onload=()=>finish(true);s.onerror=()=>finish(false);document.head.appendChild(s)})}
function patchVersion(){document.documentElement.dataset.editorialVersion=VERSION;const m=document.querySelector('meta[name="editorial-emulator-build"]');if(m)m.content=VERSION;document.title=document.title.replace(/Editorial Emulator V[\d.]+/,'Editorial Emulator V4.4');const manifest=document.querySelector('link[rel="manifest"]');if(manifest)manifest.href='./manifest.webmanifest?v=44';document.querySelectorAll('a[href]').forEach(a=>{let h=a.getAttribute('href')||'';h=h.replace(/\?v=(29|30|31|32|33|34|35|36|37|38|39|40|41|42|43)/g,'?v=44');a.setAttribute('href',h)})}
async function registerSW(){if(NATIVE_DESKTOP||!('serviceWorker' in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v=44',{scope:'./',updateViaCache:'none'});reg.update?.()}catch(e){console.info('Service Worker no disponible; la app sigue local-first.',e)}}
async function boot(){patchVersion();['30','33','36','37','38','39','41','42','43','44'].forEach(v=>css(`./css/system-v${v}.css?v=44`,`editorialV${v}`));const modules=[['./js/planner-v44.js?v=44','editorialPlannerV44'],['./js/flexible-week-v33.js?v=44','editorialFlexibleWeekV40'],['./js/catalog-v37.js?v=44','editorialCatalogV37'],['./js/catalog-v38.js?v=44','editorialCatalogV40'],['./js/dnd-v40.js?v=44','editorialDndV40'],['./js/smart-drag-v42.js?v=44','editorialSmartDragV42'],['./js/workflow-data-v43.js?v=44','editorialWorkflowDataV43'],['./js/workflow-ui-v44.js?v=44','editorialWorkflowUiV44'],['./js/workflow-create-v43.js?v=44','editorialWorkflowCreateV43'],['./js/workflow-filters-v43.js?v=44','editorialWorkflowFiltersV43'],['./js/workflow-sync-v43.js?v=44','editorialWorkflowSyncV43']];for(const [src,key] of modules)await load(src,key);patchVersion();document.documentElement.dataset.editorialBoot='ready';window.dispatchEvent(new CustomEvent('editorial:boot-ready',{detail:{version:VERSION,nativeDesktop:NATIVE_DESKTOP}}));registerSW()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
