(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='editorialEmulatorCatalogV37';
const mobile=()=>matchMedia?.('(max-width: 900px)')?.matches;
const parse=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}};
let state={open:!mobile(),expanded:false,q:'',lot:'all',...parse(localStorage.getItem(KEY),{})},mounted=false,raf=0;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function planner(){return $('#plannerV30')}
function catalog(){return $('.v37-library')}
function isOpen(){const lib=catalog(),root=planner();return !!lib&&!!root&&!lib.hidden&&!root.classList.contains('v37-catalog-closed')}
function visibleCount(){return $$('#v30Catalog .v30-source:not([hidden])').length}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;refresh()})}
function setOpen(v){state.open=!!v;if(!state.open)state.expanded=false;save();renderState();window.dispatchEvent(new CustomEvent('editorial:catalog-state',{detail:{open:state.open,expanded:state.expanded}}))}
function toggle(){setOpen(!isOpen())}
function renderState(){const root=planner(),lib=catalog();if(!root||!lib)return;root.classList.toggle('v37-catalog-closed',!state.open);root.classList.toggle('v37-catalog-expanded',!!state.expanded&&state.open&&!mobile());lib.hidden=!state.open;const exp=$('[data-v37-expand]',lib);if(exp){exp.textContent=state.expanded?'↙':'↗';exp.title=state.expanded?'Reducir biblioteca':'Ampliar biblioteca'}$$('[data-v37-lot]',lib).forEach(b=>{const on=b.dataset.v37Lot===state.lot;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});const t=$('#v38CatalogToggle');if(t){t.setAttribute('aria-expanded',state.open?'true':'false');t.classList.toggle('active',state.open);const label=$('[data-v38-label]',t),count=$('[data-v38-count]',t);if(label)label.textContent=state.open?'Cerrar contenido':'Contenido';if(count)count.textContent=String(visibleCount())}document.documentElement.dataset.catalog='v45'}
function decorateCards(){$$('#v30Catalog .v30-source').forEach(card=>{const title=$('b',card)?.textContent?.trim()||'Contenido';card.setAttribute('aria-label',title);const btn=$('.v30-add',card);if(btn&&btn.textContent!=='Elegir día')btn.textContent='Elegir día'});renderState()}
function applyBaseFilters(){const q=(state.q||'').trim().toLowerCase(),lot=state.lot||'all';let visible=0;$$('#v30Catalog .v30-source').forEach(card=>{const text=(card.textContent||'').toLowerCase(),cardLot=(card.querySelector('.lot')?.textContent||'').trim();const show=(!q||text.includes(q))&&(lot==='all'||cardLot===lot);card.hidden=!show;if(show)visible++});let empty=$('#v37FilterEmpty');if(!visible){if(!empty){empty=document.createElement('div');empty.id='v37FilterEmpty';empty.className='v37-filter-empty';empty.textContent='No hay contenidos con esos filtros.';$('#v30Catalog')?.appendChild(empty)}}else empty?.remove();renderState()}
function refresh(){if(!mounted)return;decorateCards();applyBaseFilters()}
function mount(){if(mounted)return true;const root=planner(),raw=$('.v30-catalog',root),surface=$('#v30Surface',root);if(!root||!raw||!surface)return false;mounted=true;const wb=document.createElement('div');wb.id='v37Workbench';wb.className='v37-workbench v45-drawer-workbench';surface.parentNode.insertBefore(wb,surface);wb.appendChild(surface);wb.appendChild(raw);raw.classList.add('v37-library');const oldHead=$('.v30-catalog-head',raw);if(oldHead)oldHead.innerHTML=`<div class="v37-library-title"><div><span class="eyebrow">Biblioteca</span><b>Contenido disponible</b><small>Arrastra al plan o elige un día</small></div><div class="v37-library-head-actions"><button type="button" data-v37-expand aria-label="Cambiar tamaño del panel">↗</button><button type="button" data-v37-close aria-label="Ocultar contenido">×</button></div></div>`;const tools=document.createElement('div');tools.className='v37-library-tools';tools.innerHTML=`<label class="v37-search"><span aria-hidden="true">⌕</span><input id="v37CatalogSearch" type="search" placeholder="Buscar contenido…" autocomplete="off"></label><div class="v37-lotseg" role="group" aria-label="Filtrar por lote"><button data-v37-lot="all">Todos</button><button data-v37-lot="L1">L1</button><button data-v37-lot="L2">L2</button><button data-v37-lot="L3">L3</button></div>`;raw.insertBefore(tools,$('#v30Catalog',raw));const search=$('#v37CatalogSearch');search.value=state.q||'';search.addEventListener('input',e=>{state.q=e.target.value||'';save();applyBaseFilters();window.dispatchEvent(new CustomEvent('editorial:catalog-filter'))});$$('[data-v37-lot]',tools).forEach(b=>b.onclick=()=>{state.lot=b.dataset.v37Lot;save();renderState();applyBaseFilters();window.dispatchEvent(new CustomEvent('editorial:catalog-filter'))});$('[data-v37-close]',raw).onclick=()=>setOpen(false);$('[data-v37-expand]',raw).onclick=()=>{state.expanded=!state.expanded;state.open=true;save();renderState()};let toggle=$('#v38CatalogToggle');if(!toggle){toggle=document.createElement('button');toggle.id='v38CatalogToggle';toggle.className='v38-catalog-toggle';toggle.type='button';toggle.innerHTML='<span class="v38-toggle-icon">▦</span><span data-v38-label>Contenido</span><span data-v38-count class="v38-count">0</span>';const seg=$('.v30-viewseg',root);seg?.insertAdjacentElement('afterend',toggle);toggle.addEventListener('click',toggleDrawer)}window.addEventListener('editorial:planner-rendered',schedule,{passive:true});window.addEventListener('editorial:taxonomy-changed',schedule,{passive:true});window.addEventListener('editorial:v43-changed',schedule,{passive:true});window.addEventListener('resize',()=>{if(mobile()&&state.expanded){state.expanded=false;save()}renderState()},{passive:true});decorateCards();renderState();applyBaseFilters();return true}
function toggleDrawer(){toggle()}
function boot(){if(mount())return;let tries=0;const t=setInterval(()=>{tries++;if(mount()||tries>60)clearInterval(t)},50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
const api={open:()=>setOpen(true),close:()=>setOpen(false),toggle,setHeight:()=>{},state:()=>({...state}),refresh:schedule};window.EDITORIAL_CATALOG_V37=api;window.EDITORIAL_CATALOG_V38=api;window.EDITORIAL_CATALOG_V45=api;
})();
