import {store,STORAGE_KEYS} from './store.js';
const WORKSPACE='editorial-os';
let client=null,channel=null,timer=null;
function config(){let c={url:window.EDITORIAL_SUPABASE?.url||'',key:window.EDITORIAL_SUPABASE?.key||''};try{c={...c,...JSON.parse(localStorage.getItem(STORAGE_KEYS.K_CLOUD)||'{}')}}catch{}return c}
function mergeById(remote=[],local=[]){const m=new Map(remote.map(x=>[x.id,x]));local.forEach(x=>m.set(x.id,{...(m.get(x.id)||{}),...x}));return [...m.values()]}
function mergePayload(remote,owned){const r=remote&&typeof remote==='object'?structuredClone(remote):{};const ra=r.appData||{},la=owned.appData||{};r.version=9;r.appData={...ra,...la,brands:mergeById(ra.brands,la.brands),pillars:mergeById(ra.pillars,la.pillars),families:mergeById(ra.families,la.families),customContent:mergeById(ra.customContent,la.customContent),completion:{...(ra.completion||{}),...(la.completion||{})},production:{...(ra.production||{}),...(la.production||{})},history:[...(la.history||[]),...(ra.history||[])].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,300)};r.plannerDraft=owned.plannerDraft;r.savedScenarios=mergeById(r.savedScenarios||[],owned.savedScenarios||[]);const prev=Number(r.syncMeta?.revision||0);r.syncMeta={...(r.syncMeta||{}),revision:prev+1,baseRevision:prev,deviceId:localStorage.getItem('editorialEmulatorDeviceId')||crypto.randomUUID(),productVersion:'emulator-1.0',updatedAt:new Date().toISOString()};localStorage.setItem('editorialEmulatorDeviceId',r.syncMeta.deviceId);return r}
async function session(){if(!client)return null;const {data}=await client.auth.getSession();store.setCloud({session:data.session||null});return data.session||null}
async function subscribe(){const s=await session();if(!s||!client)return;if(channel)client.removeChannel(channel);channel=client.channel(`editorial-emulator-${s.user.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'editorial_state',filter:`user_id=eq.${s.user.id}`},payload=>{if(!store.state.dirty&&payload.new?.payload){store.mergeCloudPayload(payload.new.payload);store.setCloud({status:'synced',lastPayload:payload.new.payload})}else if(payload.new?.payload){store.setCloud({status:'remote'})}}).subscribe()}
export const cloud={
 init(){const c=config();if(c.url&&c.key&&window.supabase){client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});session().then(s=>{if(s){this.pull(true);subscribe()}else store.setCloud({status:'local'})})}else store.setCloud({status:'local'})},
 async pull(silent=false){if(!client)return false;const s=await session();if(!s){if(!silent)throw new Error('No hay sesión de Supabase.');return false}store.setCloud({status:'syncing'});const {data,error}=await client.from('editorial_state').select('payload').eq('user_id',s.user.id).eq('workspace_key',WORKSPACE).maybeSingle();if(error){store.setCloud({status:'error'});if(!silent)throw error;return false}if(data?.payload){store.mergeCloudPayload(data.payload);store.setCloud({status:'synced',lastPayload:data.payload,remoteRevision:Number(data.payload.syncMeta?.revision||0)})}else store.setCloud({status:'synced'});return true},
 schedule(){clearTimeout(timer);store.setCloud({status:navigator.onLine?'pending':'error'});timer=setTimeout(()=>this.push(true),900)},
 async push(silent=false){if(!client||!navigator.onLine)return false;const s=await session();if(!s)return false;store.setCloud({status:'syncing'});const {data,error}=await client.from('editorial_state').select('payload').eq('user_id',s.user.id).eq('workspace_key',WORKSPACE).maybeSingle();if(error){store.setCloud({status:'error'});if(!silent)throw error;return false}const merged=mergePayload(data?.payload,store.exportOwned());const row={user_id:s.user.id,workspace_key:WORKSPACE,payload:merged,updated_at:new Date().toISOString()};const {error:upErr}=await client.from('editorial_state').upsert(row,{onConflict:'user_id,workspace_key'});if(upErr){store.setCloud({status:'error'});if(!silent)throw upErr;return false}store.markSynced();store.setCloud({status:'synced',lastPayload:merged,remoteRevision:Number(merged.syncMeta.revision||0)});return true},
 async signIn(email,password){if(!client)throw new Error('Configura Supabase.');const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;store.setCloud({session:data.session,status:'syncing'});await this.pull(true);await subscribe();return data.session},
 async signOut(){if(client)await client.auth.signOut();if(channel&&client)client.removeChannel(channel);channel=null;store.setCloud({session:null,status:'local'})},
 configured(){const c=config();return !!(c.url&&c.key)},getConfig:config
};
window.addEventListener('online',()=>{if(store.state.dirty)cloud.push(true)});
