import {store} from './store.js';
const DOWS=[1,2,3,4,5,6,0];
const pnames={instagram:'Instagram',tiktok:'TikTok',linkedin:'LinkedIn',youtube:'YouTube',facebook:'Facebook'};
let cacheKey='',cache=null;
function dateForDow(anchor,dow){const d=new Date(anchor+'T12:00:00');const current=d.getDay()||7,target=dow||7;d.setDate(d.getDate()+(target-current+7)%7);return d}
function build(){const s=store.state,key=`${s.dataRevision}|${s.ui.anchorDate}`;if(key===cacheKey&&cache)return cache;const out={instagram:[],tiktok:[],linkedin:[],youtube:[],facebook:[],all:[]};DOWS.forEach(dow=>{const date=dateForDow(s.ui.anchorDate,dow).toISOString().slice(0,10);(s.plannerDraft[dow]||[]).forEach((item,idx)=>{(item.platforms||[]).forEach(platform=>{const post={...item,platform,date,dow,occurrenceId:`${date}-${item.instanceId||item.templateId||item.id}-${platform}-${idx}`};out[platform]?.push(post);out.all.push(post)})})});cacheKey=key;cache=out;return out}
function media(post){return `<div class="media-sim ${String(post.lot||'L2').toLowerCase()}" data-occ="${post.occurrenceId}"><span>${esc(post.title)}</span></div>`}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function igProfile(posts,current){return `<div class="ig-app"><div class="ig-top"><span>JOC</span><span>＋ ♡ ☰</span></div><div class="ig-profile-head"><div class="ig-profile-row"><div class="ig-avatar"></div><div class="ig-stat"><b>${posts.length}</b>posts</div><div class="ig-stat"><b>12.4K</b>seguidores</div><div class="ig-stat"><b>831</b>siguiendo</div></div><div class="ig-bio"><b>JOC</b><br>Ventas, criterio y ejecución.</div><div class="ig-profile-actions"><span>Editar perfil</span><span>Compartir perfil</span><span>＋</span></div></div><div class="ig-grid">${posts.map(p=>`<div class="ig-grid-item ${p.occurrenceId===current?'sim-current':''}">${media(p)}</div>`).join('')}</div></div>`}
function igFeed(posts,current){return `<div class="ig-app"><div class="ig-top"><span>Instagram</span><span>♡ ✉</span></div>${posts.map(p=>`<article class="ig-feed-post ${p.occurrenceId===current?'sim-current':''}"><div class="ig-post-head"><span class="ig-mini-avatar"></span><span>joc · ${p.date}</span></div><div class="ig-post-media">${media(p)}</div><div class="ig-actions">♡　◯　➤</div><div class="ig-caption"><b>joc</b> ${esc(p.title)}<br><small>${esc(p.type||'Contenido')}</small></div></article>`).join('')}</div>`}
function linkedin(posts,current){return `<div class="social-feed">${posts.map(p=>`<article class="social-card ${p.occurrenceId===current?'sim-current':''}"><div class="social-card-head"><span class="social-avatar"></span><div><b>JOC</b><br><small>Ahora · ${p.date}</small></div></div><h4>${esc(p.title)}</h4><p>${esc(p.role||p.type||'Contenido editorial')}</p><div class="social-media">${media(p)}</div><p>Recomendar　Comentar　Compartir</p></article>`).join('')}</div>`}
function facebook(posts,current){return `<div class="social-feed">${posts.map(p=>`<article class="social-card ${p.occurrenceId===current?'sim-current':''}"><div class="social-card-head"><span class="social-avatar"></span><div><b>JOC</b><br><small>${p.date}</small></div></div><h4>${esc(p.title)}</h4><div class="social-media">${media(p)}</div><p>Me gusta　Comentar　Compartir</p></article>`).join('')}</div>`}
function tiktok(posts,current){return `<div class="tiktok-feed">${posts.map(p=>`<article class="tiktok-card ${p.occurrenceId===current?'sim-current':''}"><div class="media-sim ${String(p.lot||'L2').toLowerCase()}"></div><div class="tiktok-info"><b>@joc</b><p>${esc(p.title)}</p><small>${p.date}</small></div></article>`).join('')}</div>`}
function youtube(posts,current){return `<div class="yt-app"><div class="yt-top">YouTube</div>${posts.map(p=>`<article class="yt-card ${p.occurrenceId===current?'sim-current':''}"><div class="yt-thumb">${media(p)}</div><h4>${esc(p.title)}</h4><p>JOC · ${p.date} · ${esc(p.surface||'Video')}</p></article>`).join('')}</div>`}
export function feedData(){return build()}
export function renderFeed(platform,mode='profile',current=''){const posts=build()[platform]||[];if(platform==='instagram')return mode==='feed'?igFeed(posts,current):igProfile(posts,current);if(platform==='linkedin')return linkedin(posts,current);if(platform==='tiktok')return tiktok(posts,current);if(platform==='youtube')return youtube(posts,current);return facebook(posts,current)}
export function platformName(p){return pnames[p]||p}
export function simulationQueue(){return build().all.sort((a,b)=>a.date.localeCompare(b.date)||a.lot.localeCompare(b.lot))}
