(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DOWS=[1,2,3,4,5,6,0],DN={1:'Lunes',2:'Martes',3:'Miércoles',4:'Jueves',5:'Viernes',6:'Sábado',0:'Domingo'},DS={1:'Lun',2:'Mar',3:'Mié',4:'Jue',5:'Vie',6:'Sáb',0:'Dom'};
const K_SC='jocEditorialV9Scenarios',K_CURRENT='editorialEmulatorV2CurrentScenario',K_VIEW='editorialEmulatorPlannerViewV30';
let mode=localStorage.getItem(K_VIEW)||'board',renderTimer=0,drag=null,ghost=null,longPress=0,startPoint=null,lastPointer=null,autoFrame=0;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function parse(v,f){try{return JSON.parse(v)??f}catch{return f}}
function current(){const id=localStorage.getItem(K_CURRENT)||'',all=parse(localStorage.getItem(K_SC),[]);return all.find(x=>x.id===id)||null}
function slots(){const s=current()?.slots||{};const o={1:[],2:[],3:[],4:[],5:[],6:[],0:[]};DOWS.forEach(d=>o[d]=Array.isArray(s[d])?s[d]:[]);return o}
function mount(){const plan=$('#planView');if(!plan||$('#plannerV30'))return;const toolbar=$('.toolbar',plan);if(!toolbar)return;
 const el=document.createElement('section');el.id='plannerV30';el.className='v30-planner';el.innerHTML=`<div class="v30-planner-head"><div><span class="eyebrow">Planificador</span><b>3 formas de construir la misma semana</b><small>Board para arrastrar · Timeline para ordenar · Agenda para precisión</small></div><div class="v30-viewseg" role="tablist" aria-label="Vista del planificador"><button data-v30-mode="board">Board</button><button data-v30-mode="timeline">Timeline</button><button data-v30-mode="agenda">Agenda</button></div></div><div class="v30-catalog"><div class="v30-catalog-head"><b>Contenido disponible</b><span>Arrastra, toca o usa “Añadir a…”</span></div><div id="v30Catalog" class="v30-catalog-strip"></div></div><div id="v30Surface" class="v30-surface"></div><div class="v30-tip">Consejo: en iPhone mantén pulsado un contenido y arrástralo. Si prefieres no arrastrar, toca <b>Añadir a…</b>.</div>`;
 toolbar.insertAdjacentElement('afterend',el);
 $$('.v30-viewseg button',el).forEach(b=>b.onclick=()=>setMode(b.dataset.v30Mode));
 render();
 const obs=new MutationObserver(()=>scheduleRender());obs.observe($('#weekBoard'),{childList:true,subtree:true});obs.observe($('#contentRail'),{childList:true,subtree:true});
 document.addEventListener('pointermove',onPointerMove,{passive:false});document.addEventListener('pointerup',onPointerUp,{passive:false});document.addEventListener('pointercancel',cancelDrag,{passive:true});
 window.addEventListener('resize',scheduleRender,{passive:true});
}
function setMode(m){if(!['board','timeline','agenda'].includes(m))return;mode=m;localStorage.setItem(K_VIEW,m);render()}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(render,80)}
function render(){const root=$('#plannerV30');if(!root)return;$$('[data-v30-mode]',root).forEach(b=>{const on=b.dataset.v30Mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});renderCatalog();renderSurface()}
function sourceCards(){return $$('#contentRail [data-template]').map(n=>({id:n.dataset.template,title:$('b',n)?.textContent?.trim()||'Contenido',meta:$('small',n)?.textContent?.trim()||'',lot:$('.lot',n)?.textContent?.trim()||''}))}
function renderCatalog(){const el=$('#v30Catalog');if(!el)return;const list=sourceCards();el.innerHTML=list.length?list.map(x=>`<article class="v30-source" data-template="${esc(x.id)}"><span class="v30-handle" aria-hidden="true">⠿</span><div><span class="lot">${esc(x.lot)}</span><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></div><button class="v30-add" data-v30-add="${esc(x.id)}">Añadir a…</button></article>`).join(''):`<div class="v30-empty">No hay contenidos visibles. Ajusta los filtros de la bandeja de Contenidos.</div>`;
 $$('.v30-source',el).forEach(card=>bindPointer(card,{kind:'template',templateId:card.dataset.template,title:$('b',card)?.textContent||'Contenido'}));
 $$('[data-v30-add]',el).forEach(b=>b.onclick=e=>{e.stopPropagation();openAddMenu(b.dataset.v30Add,b.closest('.v30-source')?.querySelector('b')?.textContent||'Contenido')});
}
function renderSurface(){const el=$('#v30Surface');if(!el)return;const s=slots();el.className=`v30-surface v30-${mode}`;
 if(mode==='board') el.innerHTML=`<div class="v30-board">${DOWS.map(d=>dayColumn(d,s[d])).join('')}</div>`;
 else if(mode==='timeline') el.innerHTML=`<div class="v30-timeline">${DOWS.map(d=>timelineRow(d,s[d])).join('')}</div>`;
 else el.innerHTML=`<div class="v30-agenda">${DOWS.map(d=>agendaGroup(d,s[d])).join('')}</div>`;
 $$('[data-v30-item]',el).forEach(card=>bindPointer(card,{kind:'item',from:Number(card.dataset.dow),instanceId:card.dataset.v30Item,title:card.querySelector('b')?.textContent||'Contenido'}));
 $$('[data-v30-menu]',el).forEach(b=>b.onclick=e=>{e.stopPropagation();invokeOriginalMenu(Number(b.dataset.dow),b.dataset.v30Menu)});
 $$('[data-v30-addday]',el).forEach(b=>b.onclick=()=>openDayCatalog(Number(b.dataset.v30Addday)));
 $$('[data-v30-up]',el).forEach(b=>b.onclick=()=>invokeStep(Number(b.dataset.dow),b.dataset.v30Up,'up'));
 $$('[data-v30-down]',el).forEach(b=>b.onclick=()=>invokeStep(Number(b.dataset.dow),b.dataset.v30Down,'down'));
}
function itemMarkup(x,d,extra=''){return `<article class="v30-plan-card" data-v30-item="${esc(x.instanceId||x.templateId||'')}" data-dow="${d}"><span class="v30-handle">⠿</span><div class="v30-cardcopy"><span class="lot">${esc(x.lot||'')}</span><b>${esc(x.title||'Contenido')}</b><small>${esc(x.type||x.surface||'Contenido')}</small></div>${extra}<button class="v30-menu" data-v30-menu="${esc(x.instanceId||x.templateId||'')}" data-dow="${d}" aria-label="Opciones">•••</button></article>`}
function dayColumn(d,a){return `<section class="v30-day" data-drop-day="${d}"><header><div><b>${DN[d]}</b><small>${a.length} ${a.length===1?'pieza':'piezas'}</small></div><button data-v30-addday="${d}">＋</button></header><div class="v30-daylist">${a.length?a.map(x=>itemMarkup(x,d)).join(''):'<div class="v30-dropempty">Suelta contenido aquí</div>'}</div></section>`}
function timelineRow(d,a){return `<section class="v30-timeline-row" data-drop-day="${d}"><header><b>${DS[d]}</b><small>${a.length}</small><button data-v30-addday="${d}">＋ Añadir</button></header><div class="v30-timeline-track">${a.length?a.map(x=>itemMarkup(x,d)).join(''):'<div class="v30-dropempty">Sin publicaciones</div>'}</div></section>`}
function agendaGroup(d,a){return `<section class="v30-agenda-group" data-drop-day="${d}"><header><div><b>${DN[d]}</b><small>${a.length} piezas</small></div><button data-v30-addday="${d}">＋ Añadir</button></header><div>${a.length?a.map((x,i)=>itemMarkup(x,d,`<div class="v30-order"><button data-v30-up="${esc(x.instanceId||'')}" data-dow="${d}" ${i===0?'disabled':''}>↑</button><button data-v30-down="${esc(x.instanceId||'')}" data-dow="${d}" ${i===a.length-1?'disabled':''}>↓</button></div>`)).join(''):'<div class="v30-dropempty">Nada programado</div>'}</div></section>`}
function bindPointer(node,payload){node.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0)return;if(e.target.closest('button'))return;startPoint={x:e.clientX,y:e.clientY,id:e.pointerId,node,payload};lastPointer={x:e.clientX,y:e.clientY};clearTimeout(longPress);longPress=setTimeout(()=>beginDrag(e,node,payload),e.pointerType==='touch'?220:100)}}
function beginDrag(e,node,payload){if(!startPoint)return;drag={...payload,pointerId:startPoint.id};node.classList.add('v30-drag-source');ghost=document.createElement('div');ghost.className='v30-ghost';ghost.innerHTML=`<b>${esc(payload.title)}</b><small>${payload.kind==='template'?'Nuevo contenido':'Mover publicación'}</small>`;document.body.append(ghost);moveGhost(lastPointer?.x||e.clientX,lastPointer?.y||e.clientY);document.body.classList.add('v30-dragging');if(navigator.vibrate)navigator.vibrate(15)}
function onPointerMove(e){if(startPoint&&!drag){const dx=e.clientX-startPoint.x,dy=e.clientY-startPoint.y;if(Math.hypot(dx,dy)>10){clearTimeout(longPress);beginDrag(e,startPoint.node,startPoint.payload)}}if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();lastPointer={x:e.clientX,y:e.clientY};moveGhost(e.clientX,e.clientY);highlightDrop(e.clientX,e.clientY);autoScroll(e.clientX,e.clientY)}
function moveGhost(x,y){if(ghost){ghost.style.transform=`translate3d(${x+14}px,${y+14}px,0)`}}
function dropAt(x,y){return document.elementFromPoint(x,y)?.closest?.('[data-drop-day]')||null}
function highlightDrop(x,y){$$('.v30-drop-active').forEach(n=>n.classList.remove('v30-drop-active'));dropAt(x,y)?.classList.add('v30-drop-active')}
function onPointerUp(e){clearTimeout(longPress);if(!drag){startPoint=null;return}e.preventDefault();const zone=dropAt(e.clientX,e.clientY);const d=zone?Number(zone.dataset.dropDay):null;const payload=drag;cleanupDrag();if(d===null||Number.isNaN(d)){toast('Movimiento cancelado');return}if(payload.kind==='template')addTemplate(payload.templateId,d);else if(payload.from!==d)moveExisting(payload.from,payload.instanceId,d);else toast('Ya está en '+DN[d])}
function cancelDrag(){clearTimeout(longPress);cleanupDrag()}
function cleanupDrag(){cancelAnimationFrame(autoFrame);autoFrame=0;$$('.v30-drop-active,.v30-drag-source').forEach(n=>n.classList.remove('v30-drop-active','v30-drag-source'));ghost?.remove();ghost=null;drag=null;startPoint=null;document.body.classList.remove('v30-dragging')}
function autoScroll(x,y){cancelAnimationFrame(autoFrame);autoFrame=requestAnimationFrame(()=>{const m=64;let dy=0,dx=0;if(y<m)dy=-12;else if(innerHeight-y<m)dy=12;if(x<m)dx=-10;else if(innerWidth-x<m)dx=10;if(dy)window.scrollBy(0,dy);const sc=$('.v30-board')||$('.v30-catalog-strip');if(sc&&dx)sc.scrollBy(dx,0)})}
function selectDay(d){const b=$(`#dayTabs [data-day="${d}"]`);if(b&&!b.classList.contains('active'))b.click()}
function addTemplate(id,d){selectDay(d);requestAnimationFrame(()=>{const src=$(`#contentRail [data-template="${cssEsc(id)}"]`);if(src){src.click();toast(`Añadido a ${DN[d]}`);scheduleRender()}else{toast('No pude añadirlo. Quita filtros de Contenidos e inténtalo de nuevo.')}})}
function moveExisting(from,id,to){invokeOriginalMenu(from,id);setTimeout(()=>{const b=$(`#sheetBody [data-move="${to}"]`);if(b){b.click();toast(`Movido a ${DN[to]}`);scheduleRender()}else toast('No pude completar el movimiento. Usa ••• → Mover como alternativa.')},70)}
function invokeOriginalMenu(d,id){const b=$(`#weekBoard .day-card[data-instance="${cssEsc(id)}"][data-dow="${d}"] [data-menu],#weekBoard .day-card[data-instance="${cssEsc(id)}"] [data-menu]`);if(b)b.click();else toast('No encontré esa publicación en el plan activo.')}
function invokeStep(d,id,act){invokeOriginalMenu(d,id);setTimeout(()=>{const b=$(`#sheetBody [data-act="${act}"]`);if(b){b.click();scheduleRender()}},60)}
function openAddMenu(id,title){const old=$('#v30Picker');old?.remove();const p=document.createElement('div');p.id='v30Picker';p.className='v30-picker';p.innerHTML=`<div class="v30-picker-card"><header><div><small>Añadir contenido</small><b>${esc(title)}</b></div><button data-close>×</button></header><div class="v30-picker-days">${DOWS.map(d=>`<button data-pick-day="${d}"><b>${DN[d]}</b><span>＋</span></button>`).join('')}</div></div>`;document.body.append(p);p.onclick=e=>{if(e.target===p||e.target.closest('[data-close]'))p.remove();const d=e.target.closest('[data-pick-day]')?.dataset.pickDay;if(d!==undefined){p.remove();addTemplate(id,Number(d))}}}
function openDayCatalog(d){const first=$('#v30Catalog .v30-source');if(!first){toast('No hay contenidos visibles');return}const p=document.createElement('div');p.className='v30-picker';p.id='v30Picker';p.innerHTML=`<div class="v30-picker-card v30-picker-catalog"><header><div><small>${DN[d]}</small><b>Elegir contenido</b></div><button data-close>×</button></header><div class="v30-picker-list">${sourceCards().map(x=>`<button data-pick-template="${esc(x.id)}"><div><span class="lot">${esc(x.lot)}</span><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></div><span>＋</span></button>`).join('')}</div></div>`;document.body.append(p);p.onclick=e=>{if(e.target===p||e.target.closest('[data-close]'))p.remove();const id=e.target.closest('[data-pick-template]')?.dataset.pickTemplate;if(id){p.remove();addTemplate(id,d)}}}
function toast(t){const r=$('#toastRegion');if(!r)return;const n=document.createElement('div');n.className='toast';n.textContent=t;r.append(n);setTimeout(()=>n.remove(),2200)}
function cssEsc(s){return globalThis.CSS?.escape?CSS.escape(String(s)):String(s).replace(/(["'\\.#:[\]()>+~*])/g,'\\$1')}
function boot(){mount();document.documentElement.dataset.planner='v30'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
