(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s);
let active=0,current=0,finishTimer=0,blocker=null;
function mount(){if($('#eeProgress'))return;const bar=document.createElement('div');bar.id='eeProgress';bar.innerHTML='<div id="eeProgressBar"></div>';document.body.appendChild(bar);const meta=document.createElement('div');meta.id='eeProgressMeta';meta.innerHTML='<span id="eeProgressPct">0%</span><span id="eeProgressMsg">Preparando…</span>';document.body.appendChild(meta)}
function render(pct,msg){mount();current=Math.max(0,Math.min(100,Number(pct)||0));$('#eeProgressBar').style.width=`${current}%`;$('#eeProgressPct').textContent=`${Math.round(current)}%`;if(msg)$('#eeProgressMsg').textContent=msg;$('#eeProgress').classList.add('visible');$('#eeProgressMeta').classList.add('visible')}
function start(msg='Procesando…',{blocking=false,blockMessage='Esta acción necesita terminar antes de continuar.'}={}){active++;clearTimeout(finishTimer);render(Math.max(current,4),msg);if(blocking)showBlocker(blockMessage);return {update:(p,m)=>update(p,m),finish:(m)=>finish(m),fail:(m)=>fail(m)}}
function update(pct,msg){render(pct,msg)}
function finish(msg='Listo'){active=Math.max(0,active-1);render(100,msg);hideBlocker();if(active===0)finishTimer=setTimeout(()=>{$('#eeProgress')?.classList.remove('visible');$('#eeProgressMeta')?.classList.remove('visible');current=0;$('#eeProgressBar')&&( $('#eeProgressBar').style.width='0%' )},650)}
function fail(msg='No se pudo completar'){active=Math.max(0,active-1);render(100,msg);hideBlocker();const meta=$('#eeProgressMeta');if(meta)meta.style.borderColor='rgba(255,104,120,.38)';setTimeout(()=>{if(meta)meta.style.borderColor='';if(active===0){$('#eeProgress')?.classList.remove('visible');$('#eeProgressMeta')?.classList.remove('visible');current=0}},1600)}
function showBlocker(message){if(blocker)return;blocker=document.createElement('div');blocker.className='ee-blocker';blocker.innerHTML=`<div class="ee-blocker-card"><div class="ee-spinner"></div><h3>Espera un momento</h3><p>${escapeHtml(message)}</p></div>`;document.body.appendChild(blocker)}
function hideBlocker(){blocker?.remove();blocker=null}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function welcome(){if($('#eeWelcome'))return;const seen=localStorage.getItem('editorialEmulatorWelcomeV32')==='1';const wrap=document.createElement('div');wrap.id='eeWelcome';wrap.innerHTML=`<section class="ee-welcome-card"><div class="ee-welcome-mark">EE</div><div><span class="eyebrow">Editorial Emulator V3.2</span><h1>Bienvenido.</h1><p>Arma tu semana, prueba distintas vistas y revisa cómo se verá el contenido antes de publicar. Todo trabaja sobre el mismo escenario.</p></div><div class="ee-welcome-grid"><article><b>Plan</b><span>Board, Timeline y Agenda sincronizados.</span></article><article><b>Feeds</b><span>Instagram, TikTok, LinkedIn, YouTube y Facebook en Mobile/Desktop.</span></article><article><b>MCP + Cloud</b><span>Automatización externa usando el mismo Supabase.</span></article></div><div class="ee-welcome-actions"><button class="primary" data-enter>Entrar a la app</button><a href="./product.html?v=32">Qué hace la app</a><a href="./mcp.html?v=32">Configurar MCP</a></div><div class="ee-welcome-foot"><label><input type="checkbox" data-dont ${seen?'checked':''}> No mostrar esta bienvenida cada vez</label><span>La app seguirá mostrando progreso arriba cuando esté trabajando.</span></div></section>`;document.body.appendChild(wrap);const close=()=>{if(wrap.querySelector('[data-dont]')?.checked)localStorage.setItem('editorialEmulatorWelcomeV32','1');else localStorage.removeItem('editorialEmulatorWelcomeV32');wrap.classList.add('hide');setTimeout(()=>wrap.remove(),260)};wrap.querySelector('[data-enter]').onclick=close;if(seen){setTimeout(close,720)}}
function bootProgress(){const p=start('Preparando Editorial Emulator…');let x=8;const id=setInterval(()=>{x=Math.min(88,x+Math.max(2,Math.round((90-x)/6)));update(x,x<35?'Cargando interfaz…':x<65?'Preparando escenarios…':'Conectando herramientas…')},120);const done=()=>{clearInterval(id);update(96,'Casi listo…');setTimeout(()=>p.finish('Listo'),160)};if(document.readyState==='complete')done();else window.addEventListener('load',done,{once:true});setTimeout(done,2600)}
function boot(){mount();welcome();bootProgress()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.EDITORIAL_PROGRESS={start,update,finish,fail,block:showBlocker,unblock:hideBlocker};
})();
