(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let raf=0,palette=null,lastFocus=null,semQueued=false,cloudStarted=false;
function syncViewport(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const vv=window.visualViewport,w=Math.round(vv?.width||innerWidth),h=Math.round(vv?.height||innerHeight),top=Math.max(0,Math.round(vv?.offsetTop||0)),root=document.documentElement;root.style.setProperty('--vvw',`${w}px`);root.style.setProperty('--vvh',`${h}px`);root.style.setProperty('--vv-top',`${top}px`);root.dataset.viewport=w<=390?'phone-small':w<=760?'phone':w<=1100?'tablet':'desktop'})}
function improveSemantics(){if(semQueued)return;semQueued=true;requestAnimationFrame(()=>{semQueued=false;$('#fatalBanner')?.setAttribute('role','alert');$('#fatalText')?.setAttribute('aria-live','assertive');$('#autosavePill')?.setAttribute('role','status');$('#autosavePill')?.setAttribute('aria-live','polite');$('#syncPill')?.setAttribute('aria-live','polite');$('#toastRegion')?.setAttribute('role','status');$('#sheet')?.setAttribute('role','dialog');$('#sheet')?.setAttribute('aria-modal','true');$('#sheet')?.setAttribute('aria-labelledby','sheetTitle');$('#sheetClose')?.setAttribute('aria-label','Cerrar');$('#railSearch')?.setAttribute('aria-label','Buscar contenido');$('#librarySearch')?.setAttribute('aria-label','Buscar en biblioteca');$('#brandSelect')?.setAttribute('aria-label','Marca activa');$('#deviceModeSeg')?.setAttribute('aria-label','Dispositivo del visor');$('#viewModeTabs')?.setAttribute('aria-label','Modo de vista');$$('[data-nav]').forEach(b=>{if(!b.getAttribute('aria-label'))b.setAttribute('aria-label',b.textContent.trim().replace(/\s+/g,' '))});$$('.icon-btn').forEach(b=>{if(b.getAttribute('aria-label'))return;const t=b.textContent.trim();if(t==='‹')b.setAttribute('aria-label','Atrás');else if(t==='›')b.setAttribute('aria-label','Siguiente');else if(t==='×')b.setAttribute('aria-label','Cerrar');else if(t==='•••')b.setAttribute('aria-label','Más opciones')})})}
function clickNav(view){document.querySelector(`[data-nav="${view}"]`)?.click()}
function isTyping(){const a=document.activeElement;return !!a&&/^(INPUT|TEXTAREA|SELECT)$/.test(a.tagName)}
function actionItems(){const appVisible=!$('#app')?.hidden;return [appVisible&&{label:'Ir a Plan',hint:'1',run:()=>clickNav('plan')},appVisible&&{label:'Ir a Feeds',hint:'2',run:()=>clickNav('feeds')},appVisible&&{label:'Ir a Biblioteca',hint:'3',run:()=>clickNav('library')},appVisible&&{label:'Buscar contenido',hint:'⌘K',run:()=>{clickNav('plan');setTimeout(()=>$('#railSearch')?.focus(),30)}},appVisible&&{label:'Nuevo contenido',hint:'⌘N',run:()=>$('#newContentBtn')?.click()},appVisible&&{label:'Undo',hint:'⌘Z',run:()=>$('#undoBtn')?.click()},appVisible&&{label:'Redo',hint:'⇧⌘Z',run:()=>$('#redoBtn')?.click()},appVisible&&{label:'Play / Stop',hint:'Space',run:()=>$('#playBtn')?.click()},appVisible&&{label:'Borrar todo el plan',hint:'',run:()=>$('#clearPlanBtn')?.click()},appVisible&&{label:'Supabase / Cloud',hint:'',run:()=>window.EDITORIAL_CLOUD?.open?.()},{label:'Escenarios',hint:'',run:()=>appVisible?$('#scenarioHomeBtn')?.click():$('#useExistingBtn')?.click()},{label:'Cómo usar la app',hint:'?',run:()=>location.href='./help.html?v=45'}].filter(Boolean)}
function closePalette(){if(!palette)return;palette.remove();palette=null;document.body.style.removeProperty('overflow');lastFocus?.focus?.();lastFocus=null}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openPalette(){if(palette){closePalette();return}lastFocus=document.activeElement;const wrap=document.createElement('div');wrap.className='v28-command-backdrop';wrap.innerHTML=`<div class="v28-command" role="dialog" aria-modal="true" aria-label="Acciones rápidas"><div class="v28-command-search"><span>⌕</span><input id="v28CommandInput" autocomplete="off" placeholder="Buscar una acción…"></div><div id="v28CommandList" class="v28-command-list"></div></div>`;document.body.append(wrap);palette=wrap;document.body.style.overflow='hidden';wrap.addEventListener('pointerdown',e=>{if(e.target===wrap)closePalette()});const input=$('#v28CommandInput',wrap),list=$('#v28CommandList',wrap);let index=0;const render=()=>{const q=input.value.trim().toLowerCase(),items=actionItems().filter(x=>!q||x.label.toLowerCase().includes(q));index=Math.max(0,Math.min(index,Math.max(0,items.length-1)));list.innerHTML=items.length?items.map((x,i)=>`<button class="v28-command-item" data-i="${i}" data-active="${i===index}"><span>${esc(x.label)}</span><small>${esc(x.hint)}</small></button>`).join(''):'<div class="v28-command-empty">No hay acciones que coincidan.</div>';list.onclick=e=>{const i=Number(e.target.closest('[data-i]')?.dataset.i);if(Number.isFinite(i)&&items[i]){const a=items[i];closePalette();a.run()}};return items};input.addEventListener('input',()=>{index=0;render()});input.addEventListener('keydown',e=>{const items=render();if(e.key==='ArrowDown'){e.preventDefault();index=Math.min(items.length-1,index+1);render()}else if(e.key==='ArrowUp'){e.preventDefault();index=Math.max(0,index-1);render()}else if(e.key==='Enter'&&items[index]){e.preventDefault();const a=items[index];closePalette();a.run()}else if(e.key==='Escape'){e.preventDefault();closePalette()}});render();setTimeout(()=>input.focus(),0)}
function keyboard(e){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette();return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='n'&&!isTyping()){e.preventDefault();$('#newContentBtn')?.click();return}if(!e.metaKey&&!e.ctrlKey&&!e.altKey&&!isTyping()&&!$('#app')?.hidden){if(e.key==='1')clickNav('plan');if(e.key==='2')clickNav('feeds');if(e.key==='3')clickNav('library');if(e.key==='/'){e.preventDefault();clickNav('plan');setTimeout(()=>$('#railSearch')?.focus(),20)}if(e.code==='Space'){e.preventDefault();$('#playBtn')?.click()}if(e.key==='?'){e.preventDefault();location.href='./help.html?v=45'}}if(e.key==='Escape'&&palette)closePalette()}
function networkState(){const pill=$('#syncPill');if(!pill)return;if(!navigator.onLine){pill.textContent='Offline';pill.classList.remove('ok');pill.dataset.offline='true'}else if(pill.dataset.offline&&!window.EDITORIAL_CLOUD){pill.textContent='Local';delete pill.dataset.offline}}
function enhanceHelp(){if($('#v28HelpButton'))return;const actions=$('.top-actions');if(!actions)return;const b=document.createElement('a');b.id='v28HelpButton';b.className='icon-btn';b.href='./help.html?v=45';b.textContent='?';b.setAttribute('aria-label','Cómo usar la app');actions.appendChild(b)}
async function loadCloud(){if(cloudStarted)return;cloudStarted=true;try{await import('./cloud-bridge-v29.js?v=45');window.EDITORIAL_CLOUD?.start?.()}catch(error){console.info('Cloud bridge no disponible; la app continúa local-first.',error);const pill=$('#syncPill');if(pill)pill.textContent='Local'}}
function boot(){syncViewport();improveSemantics();enhanceHelp();networkState();window.visualViewport?.addEventListener('resize',syncViewport,{passive:true});window.visualViewport?.addEventListener('scroll',syncViewport,{passive:true});window.addEventListener('resize',syncViewport,{passive:true});window.addEventListener('online',networkState);window.addEventListener('offline',networkState);document.addEventListener('keydown',keyboard);['editorial:boot-ready','editorial:planner-rendered','editorial:v43-changed','editorial:taxonomy-changed'].forEach(ev=>window.addEventListener(ev,improveSemantics,{passive:true}));document.addEventListener('click',e=>{if(e.target.closest('[data-nav],#newContentBtn,#libraryCreateBtn'))setTimeout(improveSemantics,0)},{passive:true});loadCloud()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.EDITORIAL_V28={syncViewport,openPalette,closePalette,improveSemantics};
})();
