(()=>{'use strict';
const E=()=>window.EDITORIAL_V43,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let queued=false;
function summarySig(rec){const e=E(),att=e.summary(rec);return [rec.status||'idea',att?.kind||'',att?.label||'',rec.assetUrl||''].join('|')}
function summaryHTML(rec){const e=E(),att=e.summary(rec);return `<button type="button" class="v43-status-pill" data-v43-open><i></i><span>${e.esc(e.statusLabel(rec.status))}</span></button>${att?`<button type="button" class="v43-attn v43-attn-${att.kind}" data-v43-open>${e.esc(att.label)}</button>`:''}${rec.assetUrl?`<a class="v43-link-dot" href="${e.esc(e.validUrl(rec.assetUrl))}" target="_blank" rel="noopener">↗</a>`:''}<button type="button" class="v43-detail-btn" data-v43-open>☷</button>`}
function decorate(card){const e=E(),ref=e.refFor(card);if(!ref)return;const rec=e.record(ref,false),att=e.summary(rec),sig=summarySig(rec);card.dataset.v43Status=rec.status||'idea';card.dataset.v43Attention=att?.kind||'';card.classList.toggle('v43-has-pending',!!att&&att.kind!=='ready');let box=$(':scope > .v43-workflow-summary',card);if(box?.dataset.v44Sig===sig)return;if(!box){box=document.createElement('div');box.className='v43-workflow-summary';const anchor=$('.v30-add,.v30-menu,.card-menu',card);anchor?anchor.insertAdjacentElement('beforebegin',box):card.appendChild(box)}box.dataset.v44Sig=sig;box.dataset.status=rec.status||'idea';box.innerHTML=summaryHTML(rec)}
function decorateLibrary(){const e=E(),rows=$$('#libraryList .library-row'),known=new Map();$$('#v30Catalog .v30-source').forEach(c=>known.set(($('b',c)?.textContent||'').trim(),c.dataset.template));(e.app().customContent||[]).forEach(x=>known.set(x.title,x.id));rows.forEach(row=>{const id=known.get($('h4',row)?.textContent?.trim()||'');if(!id)return;row.dataset.v43Template=id;const rec=e.record({scope:'template',id,templateId:id},false),att=e.summary(rec),sig=[rec.status||'idea',att?.kind||'',att?.label||''].join('|');let box=$(':scope > .v43-library-flow',row);if(box?.dataset.v44Sig===sig)return;if(!box){box=document.createElement('div');box.className='v43-library-flow';row.appendChild(box)}box.dataset.v44Sig=sig;box.innerHTML=`<span class="v43-mini-status" data-status="${e.esc(rec.status)}"><i></i>${e.esc(e.statusLabel(rec.status))}</span>${att?`<span class="v43-mini-attn ${att.kind}">${e.esc(att.label)}</span>`:''}<button type="button" data-v43-library-open="${e.esc(id)}">Abrir ficha</button>`})}
function refresh(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;$$('#v30Catalog .v30-source,#v30Surface .v30-plan-card').forEach(decorate);decorateLibrary();window.dispatchEvent(new CustomEvent('editorial:v43-decorated',{detail:{version:'4.4'}}))})}
function title(ref){const e=E();return ref.scope==='instance'?(e.instance(ref.id)?.title||e.template(ref.templateId).title):e.template(ref.id).title}
function close(){$('#v43WorkflowOverlay')?.remove()}
function open(ref){const e=E(),rec=e.record(ref,true);e.persist();close();const o=document.createElement('div');o.id='v43WorkflowOverlay';o.className='v43-overlay';o.innerHTML=`<section class="v43-card-sheet"><div class="v43-sheet-grab"></div><header class="v43-card-head"><div><small>${ref.scope==='instance'?'Publicación de la semana':'Contenido maestro'}</small><h2>${e.esc(title(ref))}</h2></div><button type="button" data-close>×</button></header><div class="v43-card-body"><section class="v43-flow-section"><div class="v43-section-title"><span>Estado</span><small>Visible desde la tarjeta</small></div><div class="v43-status-grid">${e.STATUSES.map(([id,label])=>`<button type="button" data-status="${id}" class="${rec.status===id?'active':''}"><i></i><span>${e.esc(label)}</span></button>`).join('')}</div></section><section class="v43-flow-section"><div class="v43-section-title"><span>Enlace de trabajo</span><small>Drive, Canva, Frame.io, Dropbox o cualquier URL</small></div><div class="v43-link-editor"><input id="v43AssetUrl" type="url" placeholder="https://drive.google.com/..." value="${e.esc(rec.assetUrl||'')}"><button type="button" data-save-link>Guardar</button>${rec.assetUrl?`<a href="${e.esc(e.validUrl(rec.assetUrl))}" target="_blank" rel="noopener">Abrir ↗</a>`:''}</div></section><section class="v43-flow-section"><div class="v43-section-title"><span>Notas y correcciones</span><small>Historial interno de la ficha</small></div><div id="v43NotesThread" class="v43-notes-thread"></div><div class="v43-note-compose"><select id="v43NoteKind"><option value="note">Nota</option><option value="correction">Corrección</option></select><textarea id="v43NoteText" rows="3" placeholder="Escribe una nota o corrección…"></textarea><button type="button" data-add-note>Agregar</button></div></section></div></section>`;document.body.appendChild(o);renderNotes(ref);o.addEventListener('click',ev=>{if(ev.target===o||ev.target.closest('[data-close]'))return close();const st=ev.target.closest('[data-status]')?.dataset.status;if(st){e.setStatus(ref,st);return open(ref)}if(ev.target.closest('[data-save-link]')){if(!e.setLink(ref,$('#v43AssetUrl',o)?.value||''))e.toast('El enlace no parece válido');else{e.toast('Enlace guardado');open(ref)}return}if(ev.target.closest('[data-add-note]')){if(e.addNote(ref,$('#v43NoteText',o)?.value||'',$('#v43NoteKind',o)?.value||'note')){renderNotes(ref);$('#v43NoteText',o).value=''}else e.toast('Escribe la nota primero');return}const t=ev.target.closest('[data-note-toggle]');if(t){e.toggleNote(ref,t.dataset.noteToggle);renderNotes(ref);return}const d=ev.target.closest('[data-note-delete]');if(d){e.deleteNote(ref,d.dataset.noteDelete);renderNotes(ref)}})}
function renderNotes(ref){const e=E(),r=e.record(ref,false),box=$('#v43NotesThread');if(!box)return;const notes=[...(r?.notes||[])].sort((a,b)=>Date.parse(a.createdAt||0)-Date.parse(b.createdAt||0));box.innerHTML=notes.length?notes.map(n=>`<article class="v43-note ${n.done?'done':''} ${n.kind==='correction'?'correction':'note'}"><div class="v43-note-top"><span>${n.kind==='correction'?'Corrección':'Nota'}</span><time>${fmt(n.createdAt)}</time></div><p>${e.esc(n.text)}</p><footer><button type="button" data-note-toggle="${e.esc(n.id)}">${n.done?'Reabrir':'Marcar lista'}</button><button type="button" class="danger" data-note-delete="${e.esc(n.id)}">Eliminar</button></footer></article>`).join(''):'<div class="v43-notes-empty"><b>Sin notas todavía</b><span>Usa este espacio como conversación interna de la pieza.</span></div>'}
function fmt(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function bind(){document.addEventListener('click',ev=>{const lib=ev.target.closest('[data-v43-library-open]');if(lib){ev.preventDefault();ev.stopPropagation();return open({scope:'template',id:lib.dataset.v43LibraryOpen,templateId:lib.dataset.v43LibraryOpen})}const b=ev.target.closest('[data-v43-open]');if(!b)return;const card=b.closest('.v30-source,.v30-plan-card'),ref=E().refFor(card);if(ref){ev.preventDefault();ev.stopImmediatePropagation();open(ref)}},true);window.addEventListener('editorial:v43-changed',refresh);window.addEventListener('editorial:planner-rendered',refresh);window.addEventListener('editorial:taxonomy-changed',refresh);['#v30Catalog','#v30Surface','#libraryList'].map(s=>$(s)).filter(Boolean).forEach(r=>new MutationObserver(refresh).observe(r,{childList:true,subtree:false}));refresh()}
function boot(){if(!E()||!$('#v30Catalog'))return setTimeout(boot,50);bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.EDITORIAL_WORKFLOW_UI_V44={open,refresh};
})();